#! /bin/sh
# prerm script for apt-cacher
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove|deconfigure)
		update-inetd --remove "3142 stream tcp nowait www-data /usr/sbin/apt-cacher apt-cacher"
	;;
	
    upgrade)
	;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Script might not be present in the case of failed-upgrade, so check first
if [ -x /usr/share/apt-cacher/libcurl.pl ] ; then
    # Stop any running libcurl backend
    echo "Stopping libcurl backend"
    /usr/share/apt-cacher/libcurl.pl EXIT
fi

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/cron.daily/apt-cacher 1.7.1 -- "$@"
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/apt-cacher" ]; then
	invoke-rc.d apt-cacher stop || exit $?
fi
# End automatically added section


exit 0


